---

- ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:           "{{ aws_region }}"
    filters:
      instance-state-name: running
      'tag:type': "public"
      availability-zone: "{{ aws_az }}"
  register: proxy_instances


- name: Retrieve public hosted zone details
  environment:
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  shell: "aws route53 list-hosted-zones-by-name --dns-name {{ PublicHostedZone }}"
  register: public_hosted_zone

- set_fact: public_hosted_zone_fact={{public_hosted_zone.stdout |from_json }}

- name: A record alias to proxy instances
  route53:
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    command: create
    zone: projecteka.in
    record: test.projecteka.in
    type: A
    ttl: 300
    value: "{{ proxy_instances.instances.0.tags.Name }}.{{ PublicHostedZone }}"
    alias: True
    alias_hosted_zone_id: haproxy.projecteka.in
    overwrite: true
    wait: true