---

- name: insert frontend configuration in haproxy config
  blockinfile:
      dest: /etc/haproxy/haproxy.cfg
      marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK docker items {{ container_name}} frontend proxy config -->"
      insertafter: "#docker container haproxy config frontend"
      state: present
      block: |+1
        acl {{ container_name }} hdr(host) -i {{ container_name }}.projecteka.in
        use_backend {{container_name}} if { hdr(host) -i {{ container_name }}.projecteka.in }
  when: (container_name == "consent-manager-dev") or (container_name == "hip-dev") or (container_name == "container_name=hook")

- name: insert backend configuration in haproxy config
  blockinfile:
      dest: /etc/haproxy/haproxy.cfg
      marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK docker items {{ container_name}}  backend proxy config -->"
      insertafter: "#docker container haproxy config backend"
      state: present
      block: |+1
       backend {{ container_name }}
       mode http
       server {{ container_name }} {{ docker_host }}:{{ https_port }}
  when: (container_name == "consent-manager-dev") or (container_name == "hip-dev") or (container_name == "container_name=hook")

- name: insert frontend configuration in hiu-dev config
  blockinfile:
      dest: /etc/haproxy/haproxy.cfg
      marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK docker items {{ container_name}} frontend proxy config -->"
      insertafter: "#docker container haproxy config frontend"
      state: present
      block: |+1
        acl hiu-swagger path_beg /swagger.yaml
        acl hiu-dev path_beg /api
        use_backend hiu-dev if hiu-dev or hiu-swagger
  when: container_name == "hiu-dev"
  
- name: insert backend configuration in hiu-dev config
  blockinfile:
      dest: /etc/haproxy/haproxy.cfg
      marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK docker items {{ container_name}}  backend proxy config -->"
      insertafter: "#docker container haproxy config backend"
      state: present
      block: |+1
       backend {{ container_name }}
       mode http
       reqrep ^([^\ ]*\ /)api[/]?(.*)     \1\2
       server {{ container_name }} {{ docker_host }}:{{ https_port }}
  when: container_name == "hiu-dev"

- name: insert frontend configuration in hook config
  blockinfile:
      dest: /etc/haproxy/haproxy.cfg
      marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK docker items {{ container_name}} http_frontend proxy config -->"
      insertafter: "#docker container haproxy config http_frontend"
      state: present
      block: |+1
        acl {{ container_name }} hdr(host) -i {{ container_name }}.projecteka.in
        use_backend hook if { hdr(host) -i hook.projecteka.in }
        redirect scheme https code 301 if !{ ssl_fc } !{ hdr(host) -i {{ container_name }}.projecteka.in }
  when: container_name == "hook"
  
- name: insert backend configuration in hook config
  blockinfile:
      dest: /etc/haproxy/haproxy.cfg
      marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK docker items {{ container_name}}  backend proxy config -->"
      insertafter: "#docker container haproxy config backend"
      state: present
      block: |+1
        backend hook
        mode http
        server {{ container_name }} {{ docker_host }}:{{ https_port }}
  when: container_name == "hook"

- name: Restart haproxy
  service: name=haproxy state=reloaded